### ISSUE TITLE
Shouldn't the size of a strong type always match the underling type?

### ISSUE THREAD

**Issue by stmn-bjaehn** [rollbear/strong_type#43] opened 2024-03-22 10:28 UTC
If multiple modifiers are used, the size of the strong type seems to be doubled.
Tested with Microsoft Visual Studio Professional 2019 Version 16.11.33 C++ x64 compiler Standard: latest working draft (C++ 20)
``` cpp
using Id1 = strong::type<std::size_t, struct id1_tag, strong::equality, strong::formattable, strong::hashable>;
using Id2 = strong::type<std::size_t, struct id2_tag, strong::equality>;
using Id3 = strong::type<std::size_t, struct id3_tag, strong::formattable>;
using Id4 = strong::type<std::size_t, struct id4_tag, strong::hashable>;
using Id5 = strong::type<std::size_t, struct id5_tag, strong::equality, strong::formattable>;

std::cout << sizeof(Id1) << " | " << sizeof(strong::underlying_type_t<Id1>) << std::endl;
std::cout << sizeof(Id2) << " | " << sizeof(strong::underlying_type_t<Id2>) << std::endl;
std::cout << sizeof(Id3) << " | " << sizeof(strong::underlying_type_t<Id3>) << std::endl;
std::cout << sizeof(Id4) << " | " << sizeof(strong::underlying_type_t<Id4>) << std::endl;
std::cout << sizeof(Id5) << " | " << sizeof(strong::underlying_type_t<Id5>) << std::endl;
```
Output
![image](https://github.com/rollbear/strong_type/assets/158569688/0fb7a7f0-16cf-48b1-9867-da7bf4663054)

**Comment by rollbear** [comment] 2024-03-22 13:21
That seems to be something odd going on in MSVC. Not doing empty base class optimization properly?

gcc and clang, on Linux, both reports the same size for all, which I think it should. The library adds no data members in any case, and uses empty base classes everywhere, which shouldn't add to the size.

https://godbolt.org/z/5csMcEqrP

**Comment by rollbear** [comment] 2024-03-22 14:30
Here's a tiny reproducer.

https://godbolt.org/z/GaMTMhbjP

I'll try to report this to MS, but I find it unlikely that they'll fix it, since changing the memory layout of generated types would break ABI all over the place.

**Comment by rollbear** [comment] 2024-03-24 21:11
Closing this now, as I see this as a flaw in MSVC rather than a flaw in the library. Please reopen if you have information to the contrary.

**Closed by rollbear** 2024-03-24 21:11 UTC
